# Generated by Django 3.2.15 on 2022-08-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0002_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adm',
        ),
    ]
