# Generated by Django 3.2.15 on 2022-08-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro1app', '0003_rename_admin_adm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adm',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='adm',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='adm',
            old_name='name',
            new_name='name1',
        ),
    ]
